// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ServiceFUEN.Models.EFModels
{
    public partial class ActivityMember
    {
        public int Id { get; set; }
        public int ActivityId { get; set; }
        public int MemberId { get; set; }
        public DateTime DateJoined { get; set; }

        public virtual Activity Activity { get; set; }
        public virtual Member Member { get; set; }
    }
}