// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ServiceFUEN.Models.EFModels
{
    public partial class Administrator
    {
        public string Account { get; set; }
        public string Password { get; set; }
        public DateTime CreateTime { get; set; }
    }
}