// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ServiceFUEN.Models.EFModels
{
    public partial class AlbumItem
    {
        public int AlbumId { get; set; }
        public int PhotoId { get; set; }
        public DateTime AddTime { get; set; }

        public virtual Album Album { get; set; }
        public virtual Photo Photo { get; set; }
    }
}