// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ServiceFUEN.Models.EFModels
{
    public partial class Article
    {
        public Article()
        {
            ArticlePhotos = new HashSet<ArticlePhoto>();
            Messages = new HashSet<Message>();
        }

        public int Id { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public DateTime Time { get; set; }
        public int MemberId { get; set; }
        public int ForumId { get; set; }

        public virtual Forum Forum { get; set; }
        public virtual Member Member { get; set; }
        public virtual ICollection<ArticlePhoto> ArticlePhotos { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
    }
}