// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ServiceFUEN.Models.EFModels
{
    public partial class Forum
    {
        public Forum()
        {
            Articles = new HashSet<Article>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string About { get; set; }
        public string CoverPhoto { get; set; }

        public virtual ICollection<Article> Articles { get; set; }
    }
}