// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ServiceFUEN.Models.EFModels
{
    public partial class Instructor
    {
        public Instructor()
        {
            Activities = new HashSet<Activity>();
        }

        public int Id { get; set; }
        public string InstructorName { get; set; }
        public string ResumePhoto { get; set; }
        public string Description { get; set; }

        public virtual ICollection<Activity> Activities { get; set; }
    }
}