// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ServiceFUEN.Models.EFModels
{
    public partial class Photo
    {
        public Photo()
        {
            AlbumItems = new HashSet<AlbumItem>();
            Comments = new HashSet<Comment>();
            OthersCollections = new HashSet<OthersCollection>();
            PhotoReports = new HashSet<PhotoReport>();
            Views = new HashSet<View>();
            Tags = new HashSet<Tag>();
        }

        public int Id { get; set; }
        public string Source { get; set; }
        public string Title { get; set; }
        public int Author { get; set; }
        public string Camera { get; set; }
        public DateTime UploadTime { get; set; }

        public virtual Member AuthorNavigation { get; set; }
        public virtual ICollection<AlbumItem> AlbumItems { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<OthersCollection> OthersCollections { get; set; }
        public virtual ICollection<PhotoReport> PhotoReports { get; set; }
        public virtual ICollection<View> Views { get; set; }

        public virtual ICollection<Tag> Tags { get; set; }
    }
}