// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using ServiceFUEN.Models.EFModels;
using System;
using System.Collections.Generic;

namespace ServiceFUEN.Models.ViewModels
{
    public partial class OrderDetailVM
    {
       

        public int Id { get; set; }
        public int MemberId { get; set; }
        public DateTime OrderDate { get; set; }
        public string Address { get; set; }
        public int State { get; set; }
        public int Total { get; set; }
        public string PaymentId { get; set; }
        public int? UsedCoupon { get; set; }
        public List<OrderItemVM> orderItems { get; set; }


    }

    public static class orderdetailexten
    {
		public static OrderDetailVM Toorderdetail(this OrderDetail source)
		{
            return new OrderDetailVM
            {
                Id = source.Id,
                MemberId = source.MemberId,
                OrderDate = source.OrderDate,
                Address = source.Address,
                State = source.State,
                Total = source.Total,
                PaymentId = source.PaymentId,
                UsedCoupon = source.UsedCoupon,
                orderItems = null
			};
		}
	}
}